version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ST_TEST
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Adjust according to your needs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


volumes:
  postgres_data:
